import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { BackgroundWaves } from "@/components/svgs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const navbarData = [
    {
      data: {
        navList: [
          { text: "home", url: "/" },
          { text: "about", url: "/#" },
          { text: "services", url: "/#" },
          { text: "portfolio", url: "/#" },
          { text: "clients", url: "/#" },
        ],
      },
  },
]

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <BackgroundWaves />
        <Navbar navList={navbarData[0].data.navList} />
        {children}
      </body>
    </html>
  );
}
