import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { BackgroundWaves } from "@/components/svgs";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <BackgroundWaves />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
